# Generated by Django 4.1.6 on 2023-02-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/chairman-default.png', upload_to='media/upload'),
        ),
    ]
