# Generated by Django 4.1.7 on 2023-03-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0007_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societymember',
            name='contact_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='NoticeViewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairmanapp.notice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairmanapp.user')),
            ],
        ),
    ]
