# Generated by Django 4.1.7 on 2023-03-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0009_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default=456, max_length=10),
        ),
    ]
