# Generated by Django 4.1.7 on 2023-03-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0013_eventviewdetails_complainbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventViewDetails',
            new_name='ComplainViewDetails',
        ),
    ]
