# Generated by Django 4.1.7 on 2023-03-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0014_rename_eventviewdetails_complainviewdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainviewdetails',
            name='notice_id',
        ),
        migrations.RemoveField(
            model_name='complainviewdetails',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='ComplainBox',
        ),
        migrations.DeleteModel(
            name='ComplainViewDetails',
        ),
    ]
