# Generated by Django 4.1.7 on 2023-03-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0016_eventviewdetails_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventViewDetails',
        ),
    ]
