# Generated by Django 4.1.7 on 2023-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0019_event_pic_complainviewdetails_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='pic',
            field=models.FileField(default='media/chairman-default.png', upload_to='media/upload'),
        ),
        migrations.AddField(
            model_name='societymember',
            name='pic',
            field=models.FileField(default='media/chairman-default.png', upload_to='media/upload'),
        ),
    ]
