# Generated by Django 4.1.7 on 2023-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='pic',
            field=models.FileField(default='media/chairman-default.png', upload_to='media/upload'),
        ),
    ]
